/** @jsxImportSource @emotion/react */
import type { FunctionComponent } from 'react';
import { relativeDate } from '../utils/dateFormat';
import type { SnapshotIdViewModel } from '../models/snapshotId';
import { styles } from './styles';

type SnapshotListItemProps = {
	snapshot: SnapshotIdViewModel;
	/** Fallback revision number: total list length minus the item's index. */
	fallbackRevision: number;
	isActive: boolean;
	onSelect: () => void;
};

/**
 * A single snapshot row: revision index, snapped/modified dates + reason, and the
 * status column (legally-sensitive / comments / published state). Migrated from
 * the `snapshot-list__item` markup of restore-list.html.
 */
const SnapshotListItem: FunctionComponent<SnapshotListItemProps> = ({
	snapshot,
	fallbackRevision,
	isActive,
	onSelect,
}) => {
	const { comments } = snapshot;
	const showCommentsOff = comments.defined !== undefined && !comments.on;

	return (
		<li
			data-testid="snapshot-list-item"
			data-active={isActive}
			data-launch={snapshot.becauseOfLaunch}
			css={styles.item(isActive, snapshot.becauseOfLaunch)}
		>
			<div css={styles.itemIndex(isActive)}>
				{snapshot.revisionId ?? fallbackRevision}
			</div>

			<div css={styles.itemContent} onClick={onSelect}>
				{/* createdDateHtml is generated by our own date formatter (no user input). */}
				<h6
					css={styles.itemActualDate}
					dangerouslySetInnerHTML={{ __html: snapshot.createdDateHtml }}
				/>
				<h6 css={styles.itemRelativeDate}>
					{relativeDate(snapshot.createdDate)} ago
				</h6>
				<h6 css={styles.itemReason}>
					Last modified by: {snapshot.userEmail}
				</h6>
				<h6
					css={[
						styles.itemReason,
						snapshot.becauseOfLaunch && styles.highlightLaunch,
					]}
				>
					{snapshot.snapshotReason}
				</h6>
			</div>

			<div css={styles.itemInformation}>
				<div
					css={styles.itemStatus(snapshot.becauseOfLaunch)}
					onClick={onSelect}
				>
					<div css={styles.statusLeft}>
						{snapshot.legallySensitive && (
							<div
								data-testid="legally-sensitive"
								css={styles.legallySensitive}
							/>
						)}

						{comments.on && (
							<div css={styles.commentsOn}>
								<div css={styles.commentsImage(true)} />
								<div css={styles.commentsText}>on</div>
							</div>
						)}

						{showCommentsOff && (
							<div css={styles.commentsOff}>
								<div css={styles.commentsImage(false)} />
								<div css={styles.commentsText}>off</div>
							</div>
						)}
					</div>

					{snapshot.publishedState && (
						<div css={styles.statusRight}>{snapshot.publishedState}</div>
					)}
				</div>
			</div>
		</li>
	);
};

export { SnapshotListItem };
export type { SnapshotListItemProps };
