#!/usr/bin/env bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR=${DIR}/..

dev-nginx setup-app "$ROOT_DIR/nginx/nginx-mapping.yml"

npm install
npm run build

echo 'Setup complete! Run `sbt run` to run the app at https://restorer.local.dev-gutools.co.uk'
