name: CI
on:
    pull_request:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    CI:
        runs-on: ubuntu-latest

        permissions:
            # id-token and pull-requests required by actions-riff-raff
            id-token: write
            pull-requests: write
            # Required for `actions/checkout`
            contents: read

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: npm
                  cache-dependency-path: 'package-lock.json'

            - name: JS Build
              run: |
                  npm install
                  npm run build

            - uses: guardian/setup-scala@v1

            - name: Scala Build
              run: |
                  sbt clean compile test Debian/packageBin

            - name: Rename file to match Launch Configuration in AWS
              run: |
                  mv target/restorer2_1.0.0_all.deb restorer2.deb

            # Upload our build artifacts to Riff-Raff (well, S3)
            - uses: guardian/actions-riff-raff@v4
              with:
                  projectName: editorial-tools:flexible:restorer2
                  buildNumberOffset: 298
                  roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
                  configPath: riff-raff.yaml
                  contentDirectories: |
                      restorer2:
                        - restorer2.deb
